name: Integrate change
run-name: 'Integrating change: ${{ github.event.head_commit.message}}'

on:
  push:
    branches:
      - feat/**
      - feature/**
  pull_request:
    branches:
      - main
      - feat/**
      - feature/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Test implementation
        run: npm test

      - name: Build
        run: npm run build --if-present
